apiVersion: v1

kind: Pod

metadata:
  name: mongodb-personal-expenses-pod
  labels:
    app: mongodb-personal-expenses

spec:
  containers:
    - name: mongodb-personal-expenses-container
      image: mongo:4.0
      volumeMounts:
        - mountPath: /data/db
          name: mongodb-personal-expenses-volume

      ports:
        - containerPort: 27017
      
      envFrom:
        - configMapRef:
            name: mongodb-personal-expenses-configmap
  volumes:
    - name: mongodb-personal-expenses-volume
      hostPath:
        path: /home/matheus/Projetos/kubernetes/data/backup/
        type: DirectoryOrCreate