apiVersion: v1

kind: Service

metadata:
  name: mongodb-personal-expenses-service

spec:
  type: NodePort
  
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30000
  
  selector: 
    app: mongodb-personal-expenses